INSERT INTO public.merchant_category ("name") VALUES('Airline');
INSERT INTO public.merchant_category ("name") VALUES('Arts and crafts');
INSERT INTO public.merchant_category ("name") VALUES('Baby Products');
INSERT INTO public.merchant_category ("name") VALUES('Beauty and fragrances');
INSERT INTO public.merchant_category ("name") VALUES('Books and magazines');
INSERT INTO public.merchant_category ("name") VALUES('Camera and photographic supplies');
INSERT INTO public.merchant_category ("name") VALUES('Car and Motorcycle Rental');
INSERT INTO public.merchant_category ("name") VALUES('Cars wash');
INSERT INTO public.merchant_category ("name") VALUES('Cell phones and telephone cards');
INSERT INTO public.merchant_category ("name") VALUES('Clinics (Medical care and Dental care)');
INSERT INTO public.merchant_category ("name") VALUES('Clothing, accessories, and shoes');
INSERT INTO public.merchant_category ("name") VALUES('Convenience Store');
INSERT INTO public.merchant_category ("name") VALUES('Department Store');
INSERT INTO public.merchant_category ("name") VALUES('Drugstore');
INSERT INTO public.merchant_category ("name") VALUES('eCommerce service');
INSERT INTO public.merchant_category ("name") VALUES('Electronics (Computer, TV, House Hold)');
INSERT INTO public.merchant_category ("name") VALUES('Gifts and flowers shop');
INSERT INTO public.merchant_category ("name") VALUES('Health and personal care');
INSERT INTO public.merchant_category ("name") VALUES('Hotels, Aparment and Villas');
INSERT INTO public.merchant_category ("name") VALUES('Jewelry and Wacthes');
INSERT INTO public.merchant_category ("name") VALUES('Koperasi & UKM');
INSERT INTO public.merchant_category ("name") VALUES('Money Changer');
INSERT INTO public.merchant_category ("name") VALUES('Movies');
INSERT INTO public.merchant_category ("name") VALUES('Peripherals');
INSERT INTO public.merchant_category ("name") VALUES('Pets and animals');
INSERT INTO public.merchant_category ("name") VALUES('Public Transportation');
INSERT INTO public.merchant_category ("name") VALUES('Restaurants, Bar and Cafe');